#Projects
[[params.projects.project]]
 name = "FroshCodeCeptionTests"
 description = "Codeception Testsuite for default Responsive Theme"
 maintainers = ["fionera"]
 inStore = false

[[params.projects.project]]
 name = "FroshProfiler"
 description = "Symfony Profiler ported to Shopware with custom collectors"
 maintainers = ["shyim"]
 inStore = true

[[params.projects.project]]
 name = "FroshGrafana"
 description = "Track your Shopware and server statistics within Grafana"
 maintainers = ["Crease29"]
 inStore = false

[[params.projects.project]]
 name = "FroshTemplateMail"
 description = "Store mail templates in theme"
 maintainers = ["shyim"]
 inStore = true

[[params.projects.project]]
 name = "FroshTemplateMailMjml"
 description = "MJML Support for Template Mail"
 maintainers = ["shyim"]
 inStore = true

[[params.projects.project]]
 name = "FroshAdminer"
 description = "Adminer for Shopware"
 maintainers = ["shyim"]
 inStore = false

[[params.projects.project]]
 name = "FroshViewSnapshots"
 description = "Record or Log views"
 maintainers = ["dneustadt"]
 inStore = false

[[params.projects.project]]
 name = "FroshVariantSwitch"
 description = "Shopware plugin to switch variants in basket and checkout views"
 maintainers = ["dneustadt"]
 inStore = true

[[params.projects.project]]
 name = "FroshMailCatcher"
 description = "Simple mailcatcher integrated in Shopware"
 maintainers = ["shyim"]
 inStore = false

[[params.projects.project]]
 name = "FroshSimultaneousEditNotification"
 description = "Backend Notification when multiple users working parallel"
 maintainers = ["shyim"]
 inStore = true

[[params.projects.project]]
 name = "FroshMaintenance"
 description = "Collection of tools for Shop Maintenance"
 maintainers = ["dneustadt","eezmet"]
 inStore = false

[[params.projects.project]]
 name = "FroshPerformance"
 description = "Collection of performance improvements"
 maintainers = ["shyim","sbenmoh"]
 inStore = true

[[params.projects.project]]
 name = "FroshIonCubeChecker"
 description = "IonCube check for Shopware plugins"
 maintainers = ["larsbo"]
 inStore = true

[[params.projects.project]]
 name = "FroshWebP"
 description = "WebP Support in Shopware"
 maintainers = ["shyim"]
 inStore = true

[[params.projects.project]]
 name = "FroshMailArchive"
 description = "Simple MailArchive for Shopware"
 maintainers = ["tinect"]
 inStore = true

[[params.projects.project]]
 name = "FroshHttpCacheIpExclude"
 description = "Exclude clients from Shopware HTTP Cache by IP, Params or Cookies"
 maintainers = ["dneustadt"]
 inStore = true

[[params.projects.project]]
 name = "FroshDataTableLayout"
 description = "Adds data table to the available product layouts of categories"
 maintainers = ["dneustadt"]
 inStore = true

[[params.projects.project]]
 name = "FroshShareBasket"
 description = "Share basket as link, everywhere"
 maintainers = ["stefanpoensgen"]
 inStore = true
