name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: 0.54.0

      - name: Build 🔧 
        run: |
          hugo --gc --minify

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true
